### ISSUE TITLE
Fix issue with VMWare builds: "Waiting for HGFS kernel module to load..."

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-packer-rhel#4]
Whenever I bring up machines using the default share (e.g. the one that is used for the `/vagrant` mount by default, which could be switched to NFS/rsync/SMB, or disabled, but still...), I get the following error after a while:

```
Waiting for HGFS kernel module to load...
The HGFS kernel module was not found on the running virtual machine.
This must be installed for shared folders to work properly. Please
install the VMware tools within the guest and try again. Note that
the VMware tools installation will succeed even if HGFS fails
to properly install. Carefully read the output of the VMware tools
installation to verify the HGFS kernel modules were installed properly.
```

I'd like to not have to update all my Vagrantfiles to disable the default share or switch it to NFS, so I'd like to fix this, maybe using a technique like the one here: https://bascht.com/tech/2013/10/07/building-a-vagrant-box-with-centos-64-and-vmware/
## TODO
- [x] Update [CentOS 6 packer/vagrant cloud box](https://atlas.hashicorp.com/geerlingguy/boxes/centos6) for VMWare and VirtualBox
- [x] Update [CentOS 7 packer/vagrant cloud box](https://atlas.hashicorp.com/geerlingguy/boxes/centos7) for VMWare and VirtualBox

**Comment by geerlingguy** [comment]
Also, I can confirm that this is happening with at least CentOS 6.6; I haven't tested thoroughly on CentOS 7.x yet.

**Comment by geerlingguy** [comment]
Fix is in code, now I just need to rebuild some packer boxes and put them up on Atlas/Vagrant Cloud.

**Comment by geerlingguy** [comment]
For CentOS 7, there is no simple installation via RPM, it seems. So far I can get HGFS working if I manually install gcc + kernel headers (with `uname -r` so `kernel-devel-[kernel]`), then go through the gauntlet:

```
# After mounting the ISO on `/dev/cdrom` with 'Reinstall VMware tools' menu item.
mkdir /mnt/cdrom
mount /dev/cdrom /mnt/cdrom
cd /tmp
tar zxpf /mnt/cdrom/VMwareTools-xxxxxxx.tar.gz
umount /dev/cdrom
cd vmware-tools-distrib
# Watch the output of this command very closely. No decent error detection :P.
./vmware-install.pl --default
```

After doing that and a `vagrant reload`, the HGFS mounts work properly. Ugh.

Working on rebuilding the Packer box a few more times before I pull out more of my hair.

References:
- [VMWare Tools for Linux Guests](https://www.vmware.com/support/ws55/doc/ws_newguest_tools_linux.html#wp1127177)
- [CentOS 6.2 VMware Tools Install the Easy Way](https://gregcarriger.wordpress.com/2012/05/21/400/)

**Comment by geerlingguy** [comment]
Might have to do something like:
- [Manually mount/run/unmount VMware tools](https://github.com/chef/bento/blob/master/scripts/common/vmtools.sh#L15-L25)
- [Same thing, different ideas](https://github.com/mitchellh/packer/issues/1809)

Supposedly (according to _everything_ I've read), just installing `open-vm-tools` should be enough for CentOS 7/RHEL7, but this seems not to be the case from what I've been experiencing :(

**Comment by geerlingguy** [comment]
Fixed.

**Comment by lo5an** [comment]
I think I'm still seeing this issue with my CentOS 7.1 minimal install 

It looks like `vmware-install.pl --default` runs, but can't build kernel modules unless `gcc` and `kernel-devel` are installed.

**Comment by lo5an** [comment]
Ah, nope. I just hadn't updated to the latest version of the role properly.
